apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bako-db-credentials
  namespace: bako
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bako-db-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "arn:aws:secretsmanager:eu-north-1:483272865934:secret:rds!db-fcc62643-7739-40e7-b621-fcb09e196afa-jItOKg"